server:
  port:8080


#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
#    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
#    url: jdbc:mysql://192.168.0.64:3306/cloudtest?&useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: 111111